apiVersion: apps/v1
kind: Deployment
metadata:
  name: mykuku
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuku
  template:
    metadata:
      labels:
        app: kuku
    spec:
      containers:
        - name: mykuku
          image: praveen3362/kuku:latest  # Your Docker image
          ports:
            - containerPort: 80
          imagePullPolicy: Always
